CREATE TABLE processes_diagrams (
  id VARCHAR2(36) NOT NULL,
  name VARCHAR2(50) NOT NULL,
  description VARCHAR2(150) DEFAULT NULL,
  created TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active NUMBER(1) NOT NULL DEFAULT 1,
  diagram BLOB,
  processkey VARCHAR2(100) NOT NULL,
  type VARCHAR2(35) NOT NULL DEFAULT 'bpmn-c7',
  version NUMBER(10,0) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE (processkey)
);

CREATE TABLE revinfo (
  rev NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  revtstmp NUMBER(20,0) DEFAULT NULL,
  PRIMARY KEY (rev)
);

CREATE TABLE processes_diagrams_aud (
  id VARCHAR2(36) NOT NULL,
  rev NUMBER(10,0) NOT NULL,
  revtype NUMBER(6,0) DEFAULT NULL,
  active NUMBER(1) DEFAULT 1,
  created TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR2(150) DEFAULT NULL,
  diagram BLOB,
  diagram_mod NUMBER(1) DEFAULT NULL,
  name VARCHAR2(100) DEFAULT NULL,
  processkey VARCHAR2(100) DEFAULT NULL,
  type VARCHAR2(35) DEFAULT 'bpmn-c7',
  updated TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, rev)
);

CREATE SEQUENCE hibernate_sequence
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1;
