CREATE TABLE forms (
  id VARCHAR2(36 CHAR) NOT NULL,
  description VARCHAR2(150 CHAR),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
  active NUMBER(1) DEFAULT 1 NOT NULL,
  form_schema BLOB NOT NULL,
  formid VARCHAR2(100 CHAR) NOT NULL,
  version NUMBER(11) DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE (formid)
);
