CREATE TABLE form_usage (
    id VARCHAR2(36) NOT NULL PRIMARY KEY,
    user_id VARCHAR2(255) NOT NULL,
    form_id VARCHAR2(36) NOT NULL,
    session_id VARCHAR2(255) NOT NULL,
    opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    CONSTRAINT fk_form FOREIGN KEY (form_id) REFERENCES forms (id) ON DELETE CASCADE,
    CONSTRAINT fk_session FOREIGN KEY (session_id) REFERENCES user_sessions (id) ON DELETE CASCADE
);
