apiVersion: v2
name: cibseven-modeler
description: Base Helm chart for the modeler component of CIB seven
home: https://github.com/cibseven/cibseven-modeler
sources:
  - https://github.com/cibseven/cibseven-modeler.git

maintainers:
  - name: CIB software GmbH
    email: support@cib.de
    url: https://www.cib.de/

keywords:
  - modeler
  - cibseven-modeler
  - CIB seven

type: application

version: 0.0.0-MANAGED-BY-JENKINS

appVersion: 0.0.0-MANAGED-BY-JENKINS

dependencies:
  - name: common-tpl-lib
    version: 2.8.0
    repository: oci://harbor.cib.de/charts
