CREATE TABLE processes_diagrams (
  id VARCHAR(36) NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(150) DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  diagram BLOB,
  processkey VARCHAR(100) NOT NULL,
  type VARCHAR(35) NOT NULL DEFAULT 'bpmn-c7',
  version INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE (processkey)
);

CREATE TABLE revinfo (
  rev INTEGER NOT NULL AUTO_INCREMENT,
  revtstmp BIGINT DEFAULT NULL,
  PRIMARY KEY (rev)
);

CREATE TABLE processes_diagrams_aud (
  id VARCHAR(36) NOT NULL,
  rev INTEGER NOT NULL,
  revtype SMALLINT DEFAULT NULL,
  active BOOLEAN DEFAULT TRUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR(150) DEFAULT NULL,
  diagram BLOB,
  diagram_mod BOOLEAN DEFAULT NULL,
  name VARCHAR(100) DEFAULT NULL,
  processkey VARCHAR(100) DEFAULT NULL,
  type VARCHAR(35) DEFAULT 'bpmn-c7',
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, rev)
);

CREATE SEQUENCE hibernate_sequence
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1;
