CREATE TABLE forms (
  id VARCHAR(36) NOT NULL,
  description VARCHAR(150),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT '1970-01-01 00:00:00',
  active BOOLEAN DEFAULT TRUE,
  form_schema BLOB NOT NULL,
  formid VARCHAR(100) NOT NULL,
  version INT DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE (formid)
);
