CREATE TABLE user_sessions (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP,
  FOREIGN KEY (id) REFERENCES diagram_usage(id) ON DELETE CASCADE
);

CREATE TABLE diagram_usage (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  diagram_id VARCHAR(36) NOT NULL,
  session_id VARCHAR(36) NOT NULL,
  opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP,
  FOREIGN KEY (diagram_id) REFERENCES processes_diagrams(id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES user_sessions(id) ON DELETE CASCADE
);
